import type { Role } from '@prisma/client'

export const AUTH_CONSTANTS = {
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_SOCIAL_PROVIDER: 'INVALID_SOCIAL_PROVIDER',
  USER_NAME_REQUIRED: 'USER_NAME_REQUIRED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',

  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 64,

  SOCIAL_PROVIDERS: ['google'],

  USER_ROLES: ['USER', 'ADMIN', 'SUPER_ADMIN'] satisfies Role[],
  DEFAULT_USER_ROLE: 'USER' satisfies Role
} as const
