export const AUTH_CONSTANTS = {
  PASSWORD_MIN_LENGTH: 8,
  PASSWORD_MAX_LENGTH: 64,
  SOCIAL_PROVIDERS: ['google']
} as const

export const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_SOCIAL_PROVIDER: 'INVALID_SOCIAL_PROVIDER',
  PASSWORD_REQUIRED: 'NEW_PASSWORD_REQUIRED',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NAME_REQUIRED: 'USER_NAME_REQUIRED'
} as const

export const AUTH_FORM_FIELDS = {
  NAME: 'name',
  EMAIL: 'email',
  PASSWORD: 'password',
  NEW_PASSWORD: 'new-password'
} as const
