export type NotFound = 'NOT_FOUND'
export type Unauthorized = 'UNAUTHORIZED'
export type BadRequest = 'BAD_REQUEST'
export type Forbidden = 'FORBIDDEN'
export type Conflict = 'CONFLICT'
export type InternalServerError = 'INTERNAL_SERVER_ERROR'
