import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'

import { ROUTES } from '@/domain/navigation'
import { i18n, lang } from '@/i18n'

import '@/presentation/styles/base.sass'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => (
  <html lang={lang}>
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Link href={ROUTES.signUp}>
        Sign Up
      </Link>

      <Link href={ROUTES.signIn}>
        Sign In
      </Link>

      {i18n('appName')}

      {children}
    </body>
  </html>
)

export default RootLayout
