import classNames from 'classnames'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { lang } from '@/infrastructure/i18n'
import { Header } from '@/presentation/components/header'
import { Providers } from '@/presentation/components/providers'

import '@/presentation/styles/base.sass'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout: React.FC<React.PropsWithChildren> = async ({ children }) => (
  <Providers>
    <html data-scroll-behavior='smooth' lang={lang}>
      <body className={classNames(geistSans.variable, geistMono.variable)}>
        <Header />

        {children}
      </body>
    </html>
  </Providers>
)

export default RootLayout
