import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'

import { ROUTES } from '@/router/navigation'

import '@/styles/base.sass'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout: React.FC<React.PropsWithChildren> = ({ children }) => (
  <html lang='fr'>
    <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Link href={ROUTES.signUp}>
        Sign Up
      </Link>

      {children}
    </body>
  </html>
)

export default RootLayout;
