export const CART_CONSTANTS = {
  MAX_ITEM_QUANTITY: 10,
  MIN_ITEM_QUANTITY: 1
}

export const CART_ERRORS = {
  QUANTITY_TOO_LOW: 'CART_QUANTITY_TOO_LOW',
  QUANTITY_TOO_HIGH: 'CART_QUANTITY_TOO_HIGH'
}
